### ISSUE TITLE
Player does not disappear after a track has ended

### ISSUE THREAD

**Issue by Aaron7** [polybit/radio#10]
The player does not disappear after a track has ended.

**Comment by jdb8** [comment]
This is probably due to the lines

```javascript
if (!this.state.stream || (this.state.track && data.track.id != this.state.track.id)) {
    this.setStream(data.track.plugin, data.track.url);
}
```
(https://github.com/polybit/radio/blob/master/src/js/modules/player.js#L34-L36)

which don't account for data.track being null.
