### ISSUE TITLE
Add SoundCloud icons

### ISSUE THREAD

**Issue by Aaron7** [polybit/radio#11]
We should look at adding icons next to the track title to represent the source. I believe this is one of SoundCloud's requirements.

We could look to use an icon from here:
https://developers.soundcloud.com/docs/api/buttons-logos or use something like: https://w.soundcloud.com/icon/assets/images/orange_white_64-94fc761.png

**Comment by jdb8** [comment]
Added in https://github.com/polybit/radio/commit/b614e7eceeebc9977888bcf2dabf0d92bb1aad88.
